### ISSUE TITLE
Move from JKS --> PKCS12 Keystores

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-auth-server#376] opened 2021-12-14 17:48 UTC
It would be more secure to use PKCS12 keystores instead of JKS. This is already a requirement for FIPS 140-2.

**Comment by yuriyz** [comment] 2021-12-14 20:06
Duplicate of https://github.com/JanssenProject/jans-auth-server/issues/61

**Closed by yuriyz** 2021-12-14 20:06 UTC
Labels: enhancement
